export type Mood =
  | 'happy'
  | 'excited'
  | 'content'
  | 'neutral'
  | 'curious'
  | 'confused'
  | 'sad'
  | 'surprised'
  | 'laughing'
  | 'lovestruck'
  | 'wink'
  | 'smug'
  | 'annoyed'
  | 'grumpy'
  | 'challenging'
  | 'pout'
  | 'bored'
  | 'proud'
  | 'dizzy'
  | 'thinking'
  | 'scared'
  | 'sick'
  | 'unwell'
  | 'recovering'
  | 'listening'
  | 'talking'
  | 'dancing'
  | 'sleepy'
  | 'dozing'
  | 'birthday'
  | 'christmas'
  | 'halloween'
  | 'newyear'
  | 'valentine'
  | 'walk'
  | 'run'
  | 'jump'
  | 'flip'
  | 'backflip'
  | 'spin'
  | 'moonwalk'
  | 'wiggle'
  | 'stretch'
  | 'wave'
  | 'lookaround'
  | 'sit'
  | 'skate'
  | 'playball'
  | 'jam'
  // Set only by a click/tap reaction inside Character.tsx -- never
  // externally set, never in list()/SELECTABLE_MOODS, same treatment as
  // 'listening'/'talking' below.
  | 'poke'

export interface ChatMessage {
  role: 'user' | 'assistant'
  content: string
}
